parameters:
  - name: platformWorkloadSettings
    type: object

variables:
  - name: serviceConnection
    value: ssc-set-dev-sp001 # Must be replaced by the Workload dedicated SPN of the lowest environment . It is used for validate the pipeline run, and will be overriden by the correct SPN of each environment on runtime

stages:
  - template: /common/pipelines/01-orchestrators/alz.devops.workload.orchestrator.yml@release-engine
    parameters:
      workloadSettings:
        name: example_pattern
        configurationFilePath: ${{ parameters.platformWorkloadSettings.configurationFilePath }}
        workloadDefinitionRepositoryName: release-engine-example-workload-pattern
        environments: ${{ parameters.platformWorkloadSettings.environments }}
        workloadArtifactsPath: /patterns/example_pattern
        stages:
          # It is possible to create stages dynamically, defined at configuration level, currently used for Subscription Vending
          # - ${{ each collectionItem in parameters.platformWorkloadSettings.collection }}:
          - infrastructure:
              iac:
                name: example_pattern
                deploymentScope: Subscription
                serviceConnection: $(serviceConnection)
                iacMainFileName: workload.bicep                
                iacParameterFileName: ${{ parameters.platformWorkloadSettings.iacParameterFileName }}
                iacParameterFilesDirectory: /iac/
                
                # Use to override bicep parameters
                # customBicepParameters: '@{<param name>="$(<param value>)"}'
