parameters:
  - name: platformWorkloadSettings
    type: object

variables:
  # Workload dedicated SPN of the lowest environment.
  # It is used for validate the pipeline run, and will be overridden by the correct SPN of each environment on runtime
  # Can be set on configuration level parameters or as environment variable in the pipeline execution context
  - name: serviceConnection
    value: ServiceConnection 

stages:
  - template: /common/pipelines/01-orchestrators/alz.devops.workload.orchestrator.yml@release-engine-core
    parameters:
      workloadSettings:
        name: single_stage_pattern
        configurationFilePath: ${{ parameters.platformWorkloadSettings.configurationFilePath }}
        environments: ${{ parameters.platformWorkloadSettings.environments }}
        workloadArtifactsPath: /patterns/single_stage_pattern
        stages:
          - infrastructure:
              iac:
                name: single_stage_pattern
                deploymentScope: ResourceGroup
                serviceConnection: $(serviceConnection)
                iacMainFileName: workload.bicep
                iacParameterFileName: ${{ parameters.platformWorkloadSettings.iacParameterFileName }}