parameters:
  - name: platformWorkloadSettings
    type: object

variables:
  - name: serviceConnection
    value: ssc-set-dev-sp001 # Must be replaced by the Workload dedicated SPN of the lowest environment . It is used for validate the pipeline run, and will be overriden by the correct SPN of each environment on runtime

stages:

  - template: /common/pipelines/01-orchestrators/alz.devops.workload.orchestrator.yml@release-engine
    parameters:
      workloadSettings:
        name: multi_stage_pattern
        configurationFilePath: ${{ parameters.platformWorkloadSettings.configurationFilePath }}
        environments: ${{ parameters.platformWorkloadSettings.environments }}
        workloadArtifactsPath: /patterns/multi_stage_pattern
        stages:
          - infrastructure:
              iac:
                name: prerequisite_stage
                displayName: Prerequisite Stage
                deploymentScope: Subscription
                serviceConnection: $(serviceConnection)
                iacMainFileName: prerequisite.bicep
                iacParameterFileName: /parameters/prerequisite_stage.parameters.json

          - infrastructure:
              iac:
                name: dependent_stage1
                displayName: Dependent Stg 1
                deploymentScope: Subscription
                serviceConnection: $(serviceConnection)
                iacMainFileName: dependent.bicep
                iacParameterFileName: /parameters/dependent1.parameters.json
                dependsOn: prerequisite_stage
                lastInStage: true 

          - infrastructure:
              iac:
                name: dependent_stage2
                displayName: Dependent Stg 2
                deploymentScope: Subscription
                serviceConnection: $(serviceConnection)
                iacMainFileName: dependent.bicep
                iacParameterFileName: /parameters/dependent2.parameters.json
                dependsOn: prerequisite_stage
                lastInStage: true

          - infrastructure:
              iac:
                name: dependent_stage3
                displayName: Dependent Stg 3
                deploymentScope: Subscription
                serviceConnection: $(serviceConnection)
                iacMainFileName: dependent.bicep
                iacParameterFileName: /parameters/dependent3.parameters.json
                dependsOn: prerequisite_stage
                lastInStage: true

  - stage: debug_stage_workload
    displayName: Debug - Workload
    condition: eq( variables['System.Debug'], 'true' )
    dependsOn: []
    jobs:
      - job: debug_job
        displayName: Debug Job
        steps:
        - powershell: |
            # Shows all configurations for debugging purposes of workloadSettings
            Write-Host "\nParameters:"
            Write-Host '${{ convertToJson(parameters) }}'
            Write-Host "\nVariables:"
            Get-ChildItem env:
          displayName: Debug - Display Settings and Environment Variables