parameters:
  - name: platformWorkloadSettings
    type: object

variables:
  - name: serviceConnection
    value: ssc-set-dev-sp001 # Must be replaced by the Workload dedicated SPN of the lowest environment . It is used for validate the pipeline run, and will be overriden by the correct SPN of each environment on runtime

stages:
  - stage: debug_stage_workload
    displayName: Debug Stage Workload
    condition: eq( variables['System.Debug'], 'true' )
    jobs:
      - job: debug_job
        displayName: Debug Job
        steps:
        - powershell: |
            # Shows all configurations for debugging purposes of workloadSettings
            Write-Host "\nParameters:"
            Write-Host '${{ convertToJson(parameters) }}'
            Write-Host "\nVariables:"
            Get-ChildItem env:
          displayName: Display Settings and Environment Variables

  - template: /common/pipelines/01-orchestrators/alz.devops.workload.orchestrator.yml@release-engine
    parameters:
      workloadSettings:
        name: multi_stage_pattern
        configurationFilePath: ${{ parameters.platformWorkloadSettings.configurationFilePath }}
        environments: ${{ parameters.platformWorkloadSettings.environments }}
        workloadArtifactsPath: /patterns/multi_stage_pattern
        stages:
          - infrastructure:
              iac:
                name: sub_creation
                deploymentScope: Subscription
                serviceConnection: $(serviceConnection)
                iacMainFileName: workload.bicep                
                iacParameterFileName: ${{ parameters.platformWorkloadSettings.iacParameterFileName.sub_creation.fileName }}                

          - infrastructure:
              iac:
                name: connectivity_stamp
                deploymentScope: Subscription
                serviceConnection: $(serviceConnection)
                iacMainFileName: workload.bicep
                iacParameterFileName: ${{ parameters.platformWorkloadSettings.iacParameterFileName.connectivity_stamp.fileName }}
                dependsOn: sub_creation
                lastInStage: true 

          # - infrastructure:
          #     iac:
          #       name: stamp2
          #       deploymentScope: Subscription
          #       serviceConnection: $(serviceConnection)
          #       iacMainFileName: workload.bicep
          #       iacParameterFileName: ${{ parameters.platformWorkloadSettings.iacParameterFileName.stamp2.fileName }}
          #       dependsOn: sub_creation
          #       lastInStage: true

          # - infrastructure:
          #     iac:
          #       name: stamp3
          #       deploymentScope: Subscription
          #       serviceConnection: $(serviceConnection)
          #       iacMainFileName: workload.bicep
          #       iacParameterFileName: ${{ parameters.platformWorkloadSettings.iacParameterFileName.stamp3.fileName }}
          #       dependsOn: sub_creation
          #       lastInStage: true                